### ISSUE TITLE
资源和脚本引用丢失问题

### ISSUE THREAD

**Issue by zhaoluxyz** [SmileChen518/SolitaireCollection#2]
老兄，您的gitignore设置忽略.meta文件，其他人克隆后肯定是丢失所有引用的，方便提交下meta文件吗？

**Comment by robot518** [comment]
你不说我都没注意这个。。我之前提交的仓库都设置了.meta过滤。。这个仓库很久之前的了，我拉下来也没.meta文件。。

**Comment by robot518** [comment]
> 你不说我都没注意这个。。我之前提交的仓库都设置了.meta过滤。。这个仓库很久之前的了，我拉下来也没.meta文件。。

最新的提交修复了
